### PR TITLE
update types and kvstore nil entries

### PR DESCRIPTION
**Pull request by xgess**
update kvstore nonexistent entries in `get` requests to be nil instead of an empty string
also update all the types

depends on https://github.com/keybase/client/pull/23884

### CODE REVIEW

**Comment by xgess** [comment]
@keybase/picnicsquad

**Comment by joshblum** [comment]
@xgess @marceloneil whoever merges second can you regenerate the types from master so we dont' clobber? https://github.com/keybase/go-keybase-chat-bot/pull/71

**Comment by marceloneil** [comment]
> @xgess @marceloneil whoever merges second can you regenerate the types from master so we dont' clobber? #71

Just merged, hope that's alright!

**Comment by xgess** [comment]
> lgtm. there's the question of backwards compatibility for this bot lib too (see comment in python bot lib about the js bot lib https://github.com/keybase/pykeybasebot/pull/55/files#r414034532), whatever we decide to do there.

i dont see convenience methods like `is_present` in this library. am i missing something?

**Comment by mmou** [comment]
> > lgtm. there's the question of backwards compatibility for this bot lib too (see comment in python bot lib about the js bot lib https://github.com/keybase/pykeybasebot/pull/55/files#r414034532), whatever we decide to do there.
> 
> i dont see convenience methods like `is_present` in this library. am i missing something?

Ah yep you're right! (I think I was actually looking at some lines in an example file)

**Pull request merged**
